export const ScreenType = {
  ONBOARDING: 'ONBOARDING',
  LOGIN: 'LOGIN',
  SIGNUP: 'SIGNUP',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  CHECK_MAIL: 'CHECK_MAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
  PASSWORD_UPDATED: 'PASSWORD_UPDATED',
  PERMISSIONS: 'PERMISSIONS',
  MAP: 'MAP',
  MEETINGS: 'MEETINGS',
  MEETING_DETAILS: 'MEETING_DETAILS',
  CREATE_MEETING: 'CREATE_MEETING',
  FRIENDS: 'FRIENDS',
  FRIEND_REQUESTS: 'FRIEND_REQUESTS',
  SETTINGS: 'SETTINGS',
  NEW_MARKER: 'NEW_MARKER',
  VERIFY_EMAIL: 'VERIFY_EMAIL'
};
